CREATE TABLE "med-app_caregiver" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_caregiver_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"relationship" varchar(100),
	"phone" varchar(50),
	"email" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_condition" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_condition_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"symptoms" text,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "med-app_emergency_alert" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_emergency_alert_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"triggeredAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_journal_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_journal_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"title" varchar(255) NOT NULL,
	"content" text NOT NULL,
	"entryDate" date DEFAULT CURRENT_DATE NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_medication_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_medication_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"medicationId" integer NOT NULL,
	"userId" integer NOT NULL,
	"takenAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_medication" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_medication_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"dosage" varchar(100),
	"times" jsonb,
	"active" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_medicine" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_medicine_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"uses" text,
	"sideEffects" text
);
--> statement-breakpoint
CREATE TABLE "med-app_mood_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_mood_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"mood" integer NOT NULL,
	"notes" text,
	"entryDate" date DEFAULT CURRENT_DATE NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_symptom" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_symptom_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"severity" varchar(50) NOT NULL,
	"notes" text,
	"symptomDate" date DEFAULT CURRENT_DATE NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "med-app_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(255) NOT NULL,
	"name" varchar(255),
	"age" integer,
	"bloodType" varchar(10),
	"allergies" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "med-app_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "med-app_vital_sign" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "med-app_vital_sign_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"type" varchar(100) NOT NULL,
	"value" varchar(255) NOT NULL,
	"recordedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "med-app_caregiver" ADD CONSTRAINT "med-app_caregiver_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_emergency_alert" ADD CONSTRAINT "med-app_emergency_alert_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_journal_entry" ADD CONSTRAINT "med-app_journal_entry_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_medication_log" ADD CONSTRAINT "med-app_medication_log_medicationId_med-app_medication_id_fk" FOREIGN KEY ("medicationId") REFERENCES "public"."med-app_medication"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_medication_log" ADD CONSTRAINT "med-app_medication_log_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_medication" ADD CONSTRAINT "med-app_medication_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_mood_entry" ADD CONSTRAINT "med-app_mood_entry_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_symptom" ADD CONSTRAINT "med-app_symptom_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "med-app_vital_sign" ADD CONSTRAINT "med-app_vital_sign_userId_med-app_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."med-app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "caregiver_user_id_idx" ON "med-app_caregiver" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "condition_name_idx" ON "med-app_condition" USING btree ("name");--> statement-breakpoint
CREATE INDEX "emergency_alert_user_id_idx" ON "med-app_emergency_alert" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "emergency_alert_triggered_at_idx" ON "med-app_emergency_alert" USING btree ("triggeredAt");--> statement-breakpoint
CREATE INDEX "journal_entry_user_id_idx" ON "med-app_journal_entry" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "journal_entry_date_idx" ON "med-app_journal_entry" USING btree ("entryDate");--> statement-breakpoint
CREATE INDEX "medication_log_medication_id_idx" ON "med-app_medication_log" USING btree ("medicationId");--> statement-breakpoint
CREATE INDEX "medication_log_user_id_idx" ON "med-app_medication_log" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "medication_log_taken_at_idx" ON "med-app_medication_log" USING btree ("takenAt");--> statement-breakpoint
CREATE INDEX "medication_user_id_idx" ON "med-app_medication" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "medicine_name_idx" ON "med-app_medicine" USING btree ("name");--> statement-breakpoint
CREATE INDEX "mood_entry_user_id_idx" ON "med-app_mood_entry" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "mood_entry_date_idx" ON "med-app_mood_entry" USING btree ("entryDate");--> statement-breakpoint
CREATE INDEX "symptom_user_id_idx" ON "med-app_symptom" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "symptom_date_idx" ON "med-app_symptom" USING btree ("symptomDate");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "med-app_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "vital_sign_user_id_idx" ON "med-app_vital_sign" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "vital_sign_recorded_at_idx" ON "med-app_vital_sign" USING btree ("recordedAt");